"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SearchBar from "@/components/SearchBar";
import { usePathname } from "next/navigation"; // Import usePathname to get the current route
import { Toaster } from "@/components/ui/toaster";
import { Provider } from 'react-redux';
import store from "@/redux/store/store";
import MobileNav from "@/components/MobileNav";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Get the current route

  // Define paths where NavBar and SearchBar should not be displayed
  const hideLayoutOnPaths = ["/signin", "/register"];

  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          {/* Conditionally render NavBar and SearchBar based on the current route */}
          {!hideLayoutOnPaths.includes(pathname) && (
            <>
              <NavBar />
              <MobileNav />
              <SearchBar />
              <Toaster />
            </>
          )}
          {children}
        </body>
      </html>
    </Provider>
  );
}
